routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontController@index');

Auth::routes();

Route::middleware(['auth'])->group(function () {

  Route::get('/home', 'HomeController@index')->name('home');
  Route::delete('/home/{id}/delete', 'PageController@destroy');

  Route::resource('pages', 'PageController')->except('show');

  Route::get('/fotos/photolist', 'PhotoController@index');
  Route::get('/fotos/upload', 'PhotoController@upload');
  Route::post('add', 'PhotoController@savePicture');
  Route::get('fotos/pic/{id}', 'PhotoController@showPicture');

  Route::get('fotos/{picture}/confirm', ['as' =>'fotos.confirm', 'uses' => 'PhotoController@confirm']);
  Route::delete('fotos/{picture}/delete', ['as' => 'fotos.destroy', 'uses' => 'PhotoController@destroy']);

  Route::resource('fotos', 'PhotoController');

  Route::get('instellingen', 'OptionsController@index');
  Route::get('/instellingen/edit/{id}', ['as' => 'instellingen.edit', 'uses' => 'OptionsController@edit']);

  Route::get('user', 'UserController@index');
  Route::post('user', 'UserController@update_avatar');

  Route::resource('instellingen', 'OptionsController');

});

Route::get('/pages/{id}', ['as' => 'pages', 'uses' =>'PageController@show']);
Route::get('/qr/api', 'QrController@api');
Route::get('/qr/{id}', 'QrController@show');

resources/views/fotos/confirm.blade.php
@extends('layouts.backend')

@section('title', 'Delete '.$pictures->title)

@section('content')
    {!! Form::open(['method' => 'delete', 'route' => ['fotos.destroy', $pictures->id]]) !!}
    <div class="container">
      <div class="col-md-12">
        <div class="card">
            <div class="card-body">
              <div class="alert alert-danger alert-fotos">
                  <strong>Warning! </strong>Je staat op het punt deze foto te verwijderen! Weet je zeker dat je door wilt gaan?
              </div>
              <hr>

              {!! Form::submit('Ja, verwijder deze foto!', ['class' => 'btn btn-danger']) !!}

              <a href="{{ url('/fotos/photolist') }}" class="btn btn-success" style="float: right;">
                  <strong>Nee, breng me terug!</strong>
              </a>
            </div>
          </div>
        </div>
      </div>
    {!! Form::close() !!}
@endsection

resources/views/fotos/photolist.blade.php
@extends('layouts.backend')

@section('header')
  <h1 class="header-title">Foto's</h1>
@endsection

@section('content')

<div class="container">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        fotolijst
      </div>
      @if(Session::has('success'))
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      {{Session::get('success')}}
      </div>
      @endif
        <div class="card-body">
          <a class="foto btn btn-info" href="{{ url('/fotos/upload') }}">
            <i class="material-icons foto">control_point</i>
              Nieuw
          </a>
          <div class="table-responsive-sm">
            <table class="table table-striped table-hover">
              <thead>
                <tr>
                  <th>Naam</th>
                  <th>Foto</th>
                  <th>Status</th>
                  <th style="width:10%">View</th>
                  <th style="width:10%">Edit</th>
                  <th style="width:10%">Delete</th>
                </tr>
              </thead>
                @foreach($pictures as $picture)
                <tbody class="pages">
                  <tr>
                    <td scope="row">{{ $picture->name }}</td>
                    <td><img src="{{ asset('images/' . $picture->pic) }}" alt="foto" class="image" style="width: 80px; height: 60px;"></td>
                    <td>{{ $picture->status }}</td>
                    <td>
                      <a href="/pages/{{$picture->status}}">
                        <i class="material-icons collections">pageview</i>
                      </a>
                    </td>
                    <td>
                      <a href="{{ route('fotos.edit', $picture->id) }}">
                          <i class="material-icons update">edit</i>
                      </a>
                    </td>
                    <td>
                      <a href="{{ route('fotos.confirm', $picture->id) }}">
                        <i class="material-icons delete">delete</i>
                       </a>
                    </td>
                  </tr>
                  @endforeach
                </tbody>
            </table>
          </div>
          <?php echo $pictures->render(); ?>
        </div>
      </div>
    </div>
  </div>

@endsection

resources/views/fotos/upload.blade.php
@extends('layouts.backend')

@section('content')
@if($pictures->exists)
    {!! Form::model($pictures, ['route' => ['fotos.update', $pictures->id], 'method' => 'put']) !!}
@else
    {!! Form::open(array('url' => 'add', 'method' => 'post', 'files' => true)) !!}
@endif
    <div class="container">
      <div class="col-md-14">
        <div class="card">
          @if(Session::has('success'))
          <div class="alert alert-success alert-dismissible fade show" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          {{Session::get('success')}}
          </div>
          @endif
          <div class="card-header">
            fotolijst
          </div>
            <div class="card-body">
                  <div>
                      <div class="form-group label-floating has-success" style="width:300px;">
                        <label for="name" class="control-label">Naam:</label>
                          <input type="text" name="name" value="" class="form-control" required />
                      </div>

                      <div class="foto-pagina">
                        <h1>Pagina</h1>
                        <div class="col-md-12">
                        {!! Form::select('photo', array('' => 'Selecteer een pagina') + $pages, ['class' => 'form-control']) !!}
                    </div>
                    </div>
                  </div>

                  <div>
                    @if(!($pictures->exists))
                      {!! Form::label('Kies foto:') !!}
                      {!! Form::file('pic') !!}
                    @endif
                      <div>
                          {!! Form::submit($pictures->exists ? 'Wijzig foto' : 'Voeg toe', ['class' => 'btn btn-primary']) !!}
                      </div>
                  </div>
                </div>
            </div>
          </div>
        </div>
      </div>

    </div>

    {{ Form::close() }}

@endsection